<a href="https://colab.research.google.com/github/rezakaziz/Deeplearning-HandsOn/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
uninitialized = torch.Tensor(3,2)
rand_initialized = torch.rand(3,2)
matrix_with_ones = torch.ones(3,2)
matrix_with_zeros = torch.zeros(3,2)

In [5]:
rand_initialized.size()

torch.Size([3, 2])

In [6]:
rand_initialized.shape

torch.Size([3, 2])

In [8]:
x = torch.ones(3,2)
y = torch.ones(3,2)+2
z = torch.ones(2,1)

# * will do element wise operation and gives a tensor of the same shape
# @ to do matrix multiplication
x*y@z

tensor([[6.],
        [6.],
        [6.]])

In [16]:
# addition between two matrices
x = torch.ones(3,2)
y = torch.ones(3,2)
print("x = ", x)
print("y = ", y)
print("addition")
print("x+y = ",x+y)
print("x.add(y) = ",x.add(y))
# n-place operators follow the convention of the trailing underscore, like add_ and sub_.
print("In place addition")
x.add_(y)
print("x = ",x)

x =  tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
y =  tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
addition
x+y =  tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
x.add(y) =  tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
In place addition
x =  tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [26]:
# Concatenation
x = torch.ones(3,2)
y = torch.ones(3,2)

print("Concatenation in the first dimenstion",torch.cat((x,y),0).shape)
print("Concatenation in the second dimenstion",torch.cat((x,y),1).shape)

Concatenation in the first dimenstion torch.Size([6, 2])
Concatenation in the second dimenstion torch.Size([3, 4])


In [28]:
# Stack is adding a new dimension
x = torch.ones(3,2)
y = torch.ones(3,2)

print("Concatenation in the first dimenstion",torch.stack((x,y),0).shape)
print("Concatenation in the second dimenstion",torch.stack((x,y),1).shape)

Concatenation in the first dimenstion torch.Size([2, 3, 2])
Concatenation in the second dimenstion torch.Size([3, 2, 2])


In [29]:
#Internals of pytorch

import numpy as np

x = torch.ones(2,2)
xv = x.view(-1)
xn = x.numpy()
print(x)
print(xv)
print(xn)

tensor([[1., 1.],
        [1., 1.]])
tensor([1., 1., 1., 1.])
[[1. 1.]
 [1. 1.]]


In [31]:
x.storage()

<ipython-input-31-034ee9886547>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage()


 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]

In [32]:
xv.storage()

 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]

In [33]:
x[0,0] = 20


tensor([[20.,  1.],
        [ 1.,  1.]])

In [34]:
print(x)
print(xv)
print(xn)


tensor([[20.,  1.],
        [ 1.,  1.]])
tensor([20.,  1.,  1.,  1.])
[[20.  1.]
 [ 1.  1.]]
